type BingoCallOptions = {
    primary: string;
    alternates: string[];
};

export const bingoCalls = new Map<number, BingoCallOptions>([
    [1, { primary: "Kelly's Eye", alternates: ["Lonely as Can Be", "Single and Looking"] }],
    [2, { primary: "One Little Duck", alternates: ["Me and You in the Loo", "Just the Two of Us"] }],
    [3, { primary: "Cup of Tea", alternates: ["Time for a Wee", "You, Me, and Who's She?"] }],
    [4, { primary: "Knock at the Door", alternates: ["On the Floor with Number Four", "One More for a Score"] }],
    [5, { primary: "Man Alive", alternates: ["Too Drunk to Drive", "Did Your Wife Survive?"] }],
    [6, { primary: "Half a Dozen", alternates: ["Your Sister's Cousin", "Getting Rather Saucy"] }],
    [7, { primary: "Lucky Seven", alternates: ["One Short of Heaven", "Time to Get Even"] }],
    [8, { primary: "Garden Gate", alternates: ["Never Too Late", "Meet Your Mate"] }],
    [9, { primary: "Doctor's Orders", alternates: ["Time for Disorders", "Behind Closed Borders"] }],
    [10, { primary: "Cameron's Den", alternates: ["Boris's Pen", "Number Ten's a Mess Again"] }],
    [11, { primary: "Legs Eleven", alternates: ["My Ex-Wife's Age", "Time to Misbehave"] }],
    [12, { primary: "One Dozen", alternates: ["Cheaper by the Dozen", "Your Mother's Cousin"] }],
    [13, { primary: "Unlucky for Some", alternates: ["Marriage is Done", "Time to Run"] }],
    [14, { primary: "Valentine's Day", alternates: ["Single Again", "No Ring to Display"] }],
    [15, { primary: "Young and Keen", alternates: ["Not What You Seem", "Too Young to Dream"] }],
    [16, { primary: "Sweet Sixteen", alternates: ["Legal in Aberdeen", "Not What You Mean"] }],
    [17, { primary: "Dancing Queen", alternates: ["Never Been Seen", "Acting Like a Teen"] }],
    [18, { primary: "Coming of Age", alternates: ["Time to Engage", "Minimum Wage"] }],
    [19, { primary: "Goodbye Teens", alternates: ["Time for Some Means", "Living Beyond Your Means"] }],
    [20, { primary: "One Score", alternates: ["Plenty More in Store", "Can't Take Anymore"] }],
    [21, { primary: "Key of the Door", alternates: ["Time to Score", "Finally Legal For Sure"] }],
    [22, { primary: "Two Little Ducks", alternates: ["Quack Quack You're Back", "Swimming in Muck"] }],
    [23, { primary: "Thee and Me", alternates: ["Time for Tea and Wee", "Let's Both Disagree"] }],
    [24, { primary: "Two Dozen", alternates: ["Can't Take Any More", "Rolling on the Floor"] }],
    [25, { primary: "Duck and Dive", alternates: ["Still Alive?", "Take a Skive"] }],
    [26, { primary: "Pick and Mix", alternates: ["Up to Tricks", "In a Fix"] }],
    [27, { primary: "Gateway to Heaven", alternates: ["Not Quite Seven", "Better Than Kevin"] }],
    [28, { primary: "Over Weight", alternates: ["Time to Deflate", "Had Too Much on Your Plate"] }],
    [29, { primary: "Rise and Shine", alternates: ["Bottom of the Wine", "Looking Rather Fine"] }],
    [30, { primary: "Dirty Gertie", alternates: ["Still Flirty", "Getting Shirty"] }],
    [31, { primary: "Get Up and Run", alternates: ["Marriage Undone", "Time for Some Fun"] }],
    [32, { primary: "Buckle My Shoe", alternates: ["Nothing Left to Do", "Time for the Loo"] }],
    [33, { primary: "All the Threes", alternates: ["Time to Freeze", "Weak at the Knees"] }],
    [34, { primary: "Ask for More", alternates: ["Ex at the Door", "Rolling on the Floor"] }],
    [35, { primary: "Jump and Jive", alternates: ["Still Alive", "Take a Drive"] }],
    [36, { primary: "Three Dozen", alternates: ["Wife's Cousin", "Getting Closer to a Thousand"] }],
    [37, { primary: "More than Eleven", alternates: ["Not Quite Heaven", "Time to Get Even"] }],
    [38, { primary: "Christmas Cake", alternates: ["Wedding Mistake", "Belly Ache"] }],
    [39, { primary: "Steps", alternates: ["Time for Regrets", "Making Bad Bets"] }],
    [40, { primary: "Life Begins", alternates: ["Time for Some Sins", "Hide Your Double Chins"] }],
    [41, { primary: "Time for Fun", alternates: ["Marriage Undone", "Time to Run"] }],
    [42, { primary: "Winnie the Pooh", alternates: ["Nothing Left to Do", "Time for the Loo"] }],
    [43, { primary: "Down on Your Knees", alternates: ["Time to Freeze", "Mind the Cheese"] }],
    [44, { primary: "All the Fours", alternates: ["Ex at the Door", "Droopy Drawers"] }],
    [45, { primary: "Halfway There", alternates: ["Time for a Prayer", "Lost All Your Hair"] }],
    [46, { primary: "Up to Tricks", alternates: ["In a Fix", "Need Your Fix"] }],
    [47, { primary: "Four and Seven", alternates: ["Not Quite Heaven", "Better Than Kevin"] }],
    [48, { primary: "Four Dozen", alternates: ["Wife's Cousin", "Getting Rather Toasted"] }],
    [49, { primary: "PC", alternates: ["Time to Flee", "Need a Wee"] }],
    [50, { primary: "Half a Century", alternates: ["Looking Rather Nifty", "Getting Thrifty"] }],
    [51, { primary: "Tweak of the Thumb", alternates: ["Time for Some Rum", "Looking Rather Glum"] }],
    [52, { primary: "Danny La Rue", alternates: ["Nothing Left to Do", "Time for the Loo"] }],
    [53, { primary: "Here Comes Herbie", alternates: ["Time to Scurvy", "Getting Rather Nervy"] }],
    [54, { primary: "Clean the Floor", alternates: ["Ex at the Door", "Can't Take Anymore"] }],
    [55, { primary: "All the Fives", alternates: ["Still Alive", "Take a Skive"] }],
    [56, { primary: "Was She Worth It", alternates: ["Time to Quit", "Having a Fit"] }],
    [57, { primary: "Heinz Varieties", alternates: ["Time for Societies", "Various Anxieties"] }],
    [58, { primary: "Make Them Wait", alternates: ["Getting Rather Late", "Put on Weight"] }],
    [59, { primary: "Brighton Line", alternates: ["Feeling Fine", "Need More Wine"] }],
    [60, { primary: "Five Dozen", alternates: ["Getting Rather Frozen", "Time for Dozin'"] }],
    [61, { primary: "Baker's Bun", alternates: ["Time to Run", "Not Much Fun"] }],
    [62, { primary: "Turn the Screw", alternates: ["Nothing Left to Do", "Time for the Loo"] }],
    [63, { primary: "Tickle Me", alternates: ["Time to Flee", "Need a Wee"] }],
    [64, { primary: "Red Raw", alternates: ["Ex at the Door", "On the Floor"] }],
    [65, { primary: "Old Age Pension", alternates: ["Time for Tension", "Lost Your Pension"] }],
    [66, { primary: "Clickety Click", alternates: ["Getting Rather Sick", "Time for a Quick Pick"] }],
    [67, { primary: "Made in Heaven", alternates: ["Better Than Kevin", "Not Quite Seven"] }],
    [68, { primary: "Saving Grace", alternates: ["Pick Up the Pace", "Red in the Face"] }],
    [69, { primary: "Either Way Up", alternates: ["Time's Up", "Bottom's Up"] }],
    [70, { primary: "Three Score and Ten", alternates: ["Three Score When?", "Remember When"] }],
    [71, { primary: "Bang on the Drum", alternates: ["Time for Some Rum", "Looking Rather Glum"] }],
    [72, { primary: "Six Dozen", alternates: ["Wife's Cousin", "Getting Rather Toasted"] }],
    [73, { primary: "Queen Bee", alternates: ["Time to Flee", "Need a Wee"] }],
    [74, { primary: "Hit the Floor", alternates: ["Ex at the Door", "Can't Take Anymore"] }],
    [75, { primary: "Strive and Strive", alternates: ["Barely Alive", "Last to Arrive"] }]
]); 